[arduino]
port = /dev/serial0
baudrate = 115200
[hard]
;[m]
radius = 0.06
[motor]
left_pwm = 26
left_phase = 19
right_pwm = 20
right_phase = 21
duty = 60
base_duty = 50
[pid]
kp = 0.6
ki = 0.05
kd = 0.1
